export interface Language {
  code: string;
  name: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { name: 'Afar', code: 'aa' },
  { name: 'Abkhazian', code: 'ab' },
  { name: 'Avestan', code: 'ae' },
  { name: 'Afrikaans', code: 'af-ZA' }, // Specific for South Africa
  { name: 'Akan', code: 'ak' }, // Includes Twi, Fante
  { name: 'Amharic', code: 'am-ET' },
  { name: 'Aragonese', code: 'an' },
  { name: 'Arabic (Egypt)', code: 'ar-EG' },
  { name: 'Arabic (Saudi Arabia)', code: 'ar-SA' },
  { name: 'Assamese', code: 'as-IN' },
  { name: 'Avaric', code: 'av' },
  { name: 'Aymara', code: 'ay-BO' },
  { name: 'Azerbaijani', code: 'az-AZ' },
  { name: 'Bashkir', code: 'ba-RU' },
  { name: 'Belarusian', code: 'be-BY' },
  { name: 'Bulgarian', code: 'bg-BG' },
  { name: 'Bihari', code: 'bh' },
  { name: 'Bislama', code: 'bi-VU' },
  { name: 'Bambara', code: 'bm-ML' },
  { name: 'Bengali (Bangladesh)', code: 'bn-BD' },
  { name: 'Bengali (India)', code: 'bn-IN' },
  { name: 'Tibetan', code: 'bo-CN' },
  { name: 'Breton', code: 'br-FR' },
  { name: 'Bosnian', code: 'bs-BA' },
  { name: 'Catalan', code: 'ca-ES' },
  { name: 'Chechen', code: 'ce-RU' },
  { name: 'Chamorro', code: 'ch-GU' },
  { name: 'Corsican', code: 'co-FR' },
  { name: 'Cree', code: 'cr' },
  { name: 'Czech', code: 'cs-CZ' },
  { name: 'Church Slavic', code: 'cu' },
  { name: 'Chuvash', code: 'cv-RU' },
  { name: 'Welsh', code: 'cy-GB' },
  { name: 'Danish', code: 'da-DK' },
  { name: 'German (Germany)', code: 'de-DE' },
  { name: 'German (Austria)', code: 'de-AT' },
  { name: 'Divehi', code: 'dv-MV' },
  { name: 'Dzongkha', code: 'dz-BT' },
  { name: 'Ewe', code: 'ee-GH' }, // Ghanaian language
  { name: 'Greek', code: 'el-GR' },
  { name: 'English (US)', code: 'en-US' },
  { name: 'English (UK)', code: 'en-GB' },
  { name: 'English (Australia)', code: 'en-AU' },
  { name: 'English (Canada)', code: 'en-CA' },
  { name: 'English (Ghana)', code: 'en-GH' },
  { name: 'Esperanto', code: 'eo' },
  { name: 'Spanish (Spain)', code: 'es-ES' },
  { name: 'Spanish (Mexico)', code: 'es-MX' },
  { name: 'Estonian', code: 'et-EE' },
  { name: 'Basque', code: 'eu-ES' },
  { name: 'Persian', code: 'fa-IR' },
  { name: 'Fulah', code: 'ff-CM' }, // Fulani, across West/Central Africa
  { name: 'Finnish', code: 'fi-FI' },
  { name: 'Fijian', code: 'fj-FJ' },
  { name: 'Faroese', code: 'fo-FO' },
  { name: 'French (France)', code: 'fr-FR' },
  { name: 'French (Canada)', code: 'fr-CA' },
  { name: 'Western Frisian', code: 'fy-NL' },
  { name: 'Irish', code: 'ga-IE' },
  { name: 'Ga', code: 'gaa-GH' }, // Ghanaian language (sometimes 'ga' is used, but 'gaa' is more specific)
  { name: 'Scottish Gaelic', code: 'gd-GB' },
  { name: 'Galician', code: 'gl-ES' },
  { name: 'Guarani', code: 'gn-PY' },
  { name: 'Gujarati', code: 'gu-IN' },
  { name: 'Manx', code: 'gv-IM' },
  { name: 'Hausa', code: 'ha-NG' },
  { name: 'Hebrew', code: 'he-IL' }, // Also iw-IL
  { name: 'Hindi', code: 'hi-IN' },
  { name: 'Hiri Motu', code: 'ho-PG' },
  { name: 'Croatian', code: 'hr-HR' },
  { name: 'Haitian Creole', code: 'ht-HT' },
  { name: 'Hungarian', code: 'hu-HU' },
  { name: 'Armenian', code: 'hy-AM' },
  { name: 'Herero', code: 'hz-NA' },
  { name: 'Interlingua (International Auxiliary Language Association)', code: 'ia' },
  { name: 'Indonesian', code: 'id-ID' },
  { name: 'Interlingue', code: 'ie' },
  { name: 'Igbo', code: 'ig-NG' },
  { name: 'Sichuan Yi', code: 'ii-CN' },
  { name: 'Inupiaq', code: 'ik-US' },
  { name: 'Ido', code: 'io' },
  { name: 'Icelandic', code: 'is-IS' },
  { name: 'Italian', code: 'it-IT' },
  { name: 'Inuktitut', code: 'iu-CA' },
  { name: 'Japanese', code: 'ja-JP' },
  { name: 'Javanese', code: 'jv-ID' }, // Also jw-ID
  { name: 'Georgian', code: 'ka-GE' },
  { name: 'Kongo', code: 'kg-CD' },
  { name: 'Kikuyu', code: 'ki-KE' },
  { name: 'Kwanyama', code: 'kj-AO' },
  { name: 'Kazakh', code: 'kk-KZ' },
  { name: 'Kalaallisut', code: 'kl-GL' },
  { name: 'Khmer', code: 'km-KH' },
  { name: 'Kannada', code: 'kn-IN' },
  { name: 'Korean', code: 'ko-KR' },
  { name: 'Kanuri', code: 'kr-NG' },
  { name: 'Kashmiri', code: 'ks-IN' },
  { name: 'Kurdish (Kurmanji)', code: 'ku-TR' },
  { name: 'Komi', code: 'kv-RU' },
  { name: 'Cornish', code: 'kw-GB' },
  { name: 'Kyrgyz', code: 'ky-KG' },
  { name: 'Latin', code: 'la' },
  { name: 'Luxembourgish', code: 'lb-LU' },
  { name: 'Ganda', code: 'lg-UG' },
  { name: 'Limburgish', code: 'li-NL' },
  { name: 'Lingala', code: 'ln-CD' },
  { name: 'Lao', code: 'lo-LA' },
  { name: 'Lithuanian', code: 'lt-LT' },
  { name: 'Luba-Katanga', code: 'lu-CD' },
  { name: 'Latvian', code: 'lv-LV' },
  { name: 'Malagasy', code: 'mg-MG' },
  { name: 'Marshallese', code: 'mh-MH' },
  { name: 'Maori', code: 'mi-NZ' },
  { name: 'Macedonian', code: 'mk-MK' },
  { name: 'Malayalam', code: 'ml-IN' },
  { name: 'Mongolian', code: 'mn-MN' },
  { name: 'Marathi', code: 'mr-IN' },
  { name: 'Malay', code: 'ms-MY' },
  { name: 'Maltese', code: 'mt-MT' },
  { name: 'Burmese', code: 'my-MM' },
  { name: 'Nauruan', code: 'na-NR' },
  { name: 'Norwegian Bokmål', code: 'nb-NO' },
  { name: 'North Ndebele', code: 'nd-ZW' },
  { name: 'Nepali', code: 'ne-NP' },
  { name: 'Ndonga', code: 'ng-NA' },
  { name: 'Dutch (Netherlands)', code: 'nl-NL' },
  { name: 'Norwegian Nynorsk', code: 'nn-NO' },
  { name: 'Norwegian', code: 'no-NO' }, // Generic Norwegian, often defaults to Bokmål
  { name: 'South Ndebele', code: 'nr-ZA' },
  { name: 'Navajo', code: 'nv-US' },
  { name: 'Chichewa', code: 'ny-MW' }, // Also Nyanja
  { name: 'Occitan', code: 'oc-FR' },
  { name: 'Ojibwa', code: 'oj-CA' },
  { name: 'Oromo', code: 'om-ET' },
  { name: 'Oriya', code: 'or-IN' },
  { name: 'Ossetian', code: 'os-RU' },
  { name: 'Punjabi (Gurmukhi)', code: 'pa-IN' },
  { name: 'Pali', code: 'pi' },
  { name: 'Polish', code: 'pl-PL' },
  { name: 'Pashto', code: 'ps-AF' },
  { name: 'Portuguese (Portugal)', code: 'pt-PT' },
  { name: 'Portuguese (Brazil)', code: 'pt-BR' },
  { name: 'Quechua', code: 'qu-PE' },
  { name: 'Romansh', code: 'rm-CH' },
  { name: 'Kirundi', code: 'rn-BI' },
  { name: 'Romanian', code: 'ro-RO' },
  { name: 'Russian', code: 'ru-RU' },
  { name: 'Kinyarwanda', code: 'rw-RW' },
  { name: 'Sanskrit', code: 'sa-IN' },
  { name: 'Sardinian', code: 'sc-IT' },
  { name: 'Sindhi', code: 'sd-PK' },
  { name: 'Northern Sami', code: 'se-NO' },
  { name: 'Sango', code: 'sg-CF' },
  { name: 'Sinhala', code: 'si-LK' },
  { name: 'Slovak', code: 'sk-SK' },
  { name: 'Slovenian', code: 'sl-SI' },
  { name: 'Samoan', code: 'sm-WS' },
  { name: 'Shona', code: 'sn-ZW' },
  { name: 'Somali', code: 'so-SO' },
  { name: 'Albanian', code: 'sq-AL' },
  { name: 'Serbian', code: 'sr-RS' },
  { name: 'Swati', code: 'ss-SZ' },
  { name: 'Southern Sotho', code: 'st-LS' },
  { name: 'Sundanese', code: 'su-ID' },
  { name: 'Swedish', code: 'sv-SE' },
  { name: 'Swahili', code: 'sw-KE' },
  { name: 'Tamil', code: 'ta-IN' },
  { name: 'Telugu', code: 'te-IN' },
  { name: 'Tajik', code: 'tg-TJ' },
  { name: 'Thai', code: 'th-TH' },
  { name: 'Tigrinya', code: 'ti-ET' },
  { name: 'Turkmen', code: 'tk-TM' },
  { name: 'Tagalog (Filipino)', code: 'tl-PH' },
  { name: 'Tswana', code: 'tn-BW' },
  { name: 'Tongan', code: 'to-TO' },
  { name: 'Turkish', code: 'tr-TR' },
  { name: 'Tsonga', code: 'ts-ZA' },
  { name: 'Tatar', code: 'tt-RU' },
  { name: 'Twi', code: 'tw' }, // Often covered by Akan 'ak', but added for explicitness if API supports it separately
  { name: 'Tahitian', code: 'ty-PF' },
  { name: 'Uyghur', code: 'ug-CN' },
  { name: 'Ukrainian', code: 'uk-UA' },
  { name: 'Urdu', code: 'ur-PK' },
  { name: 'Uzbek', code: 'uz-UZ' },
  { name: 'Venda', code: 've-ZA' },
  { name: 'Vietnamese', code: 'vi-VN' },
  { name: 'Volapük', code: 'vo' },
  { name: 'Walloon', code: 'wa-BE' },
  { name: 'Wolof', code: 'wo-SN' },
  { name: 'Xhosa', code: 'xh-ZA' },
  { name: 'Yiddish', code: 'yi-US' },
  { name: 'Yoruba', code: 'yo-NG' },
  { name: 'Zhuang', code: 'za-CN' },
  { name: 'Chinese (Simplified)', code: 'zh-CN' }, // Common alias
  { name: 'Chinese (Traditional)', code: 'zh-TW' }, // Common alias
  { name: 'Zulu', code: 'zu-ZA' }
];
